version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3

  kafka2:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9093:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3

  kafka3:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9094:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3

  producer:
    restart: on-failure
    build:
      context: bins
      dockerfile: Dockerfile.producer
    environment:
      KAFKA_BROKERS: kafka1:9092,kafka2:9092,kafka3:9092
      KAFKA_TOPIC: ABC
      MESSAGE_INTERVAL: 30s
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  consumer:
    restart: on-failure
    build:
      context: bins
      dockerfile: Dockerfile.consumer
    environment:
      KAFKA_BROKERS: kafka1:9092,kafka2:9092,kafka3:9092
      KAFKA_TOPIC: ABC
      MESSAGE_INTERVAL: 30s
    depends_on:
      - kafka1
      - kafka2
      - kafka3
